const dubaiListings = [
  {
    id: '1',
    name: 'Dubai Marina Apartment',
    type: 'rent',
    regularPrice: 3200,
    discountPrice: 2900,
    offer: true,
    imageUrls: ['/1.jpg'],
    bedrooms: 2,
    bathrooms: 2,
    address: 'Marina, Dubai',
    description: 'Beautiful marina view apartment with 2 bedrooms',
  },
  {
    id: '2',
    name: 'Palm Jumeirah Villa',
    type: 'sale',
    regularPrice: 520000,
    discountPrice: 490000,
    offer: false,
    imageUrls: ['/2.jpg'],
    bedrooms: 5,
    bathrooms: 6,
    address: 'Palm Jumeirah, Dubai',
    description: 'Luxurious beachfront villa with pool and garden',
  },
  {
    id: '3',
    name: 'Downtown Apartment',
    type: 'rent',
    regularPrice: 2800,
    discountPrice: 2500,
    offer: true,
    imageUrls: ['/3.jpg'],
    bedrooms: 1,
    bathrooms: 1,
    address: 'Downtown, Dubai',
    description: 'Modern downtown apartment close to metro',
  },
  {
    id: '4',
    name: 'Burj Views Apartment',
    type: 'sale',
    regularPrice: 600000,
    discountPrice: 580000,
    offer: true,
    imageUrls: ['/4.jpg'],
    bedrooms: 3,
    bathrooms: 3,
    address: 'Burj Khalifa Blvd, Dubai',
    description: 'Iconic views from your living room',
  },
  {
    id: '5',
    name: 'Business Bay Flat',
    type: 'rent',
    regularPrice: 3000,
    discountPrice: 2750,
    offer: true,
    imageUrls: ['/5.jpg'],
    bedrooms: 2,
    bathrooms: 2,
    address: 'Business Bay, Dubai',
    description: 'Bright and spacious apartment in the business district',
  },
  {
    id: '6',
    name: 'JVC Townhouse',
    type: 'sale',
    regularPrice: 450000,
    discountPrice: 430000,
    offer: true,
    imageUrls: ['/6.jpg'],
    bedrooms: 4,
    bathrooms: 4,
    address: 'Jumeirah Village Circle, Dubai',
    description: 'Family-friendly townhouse with green space',
  },
  {
    id: '7',
    name: 'Al Barsha Studio',
    type: 'rent',
    regularPrice: 2200,
    discountPrice: 2000,
    offer: false,
    imageUrls: ['/7.jpg'],
    bedrooms: 1,
    bathrooms: 1,
    address: 'Al Barsha, Dubai',
    description: 'Affordable studio near the Mall of the Emirates',
  },
  {
    id: '8',
    name: 'Arabian Ranches Villa',
    type: 'sale',
    regularPrice: 700000,
    discountPrice: 680000,
    offer: true,
    imageUrls: ['/8.jpg'],
    bedrooms: 5,
    bathrooms: 5,
    address: 'Arabian Ranches, Dubai',
    description: 'Spacious family villa with garden and community park',
  },
];

export default dubaiListings;
